=== akhilvofficial9/XML/Kiet.dtd
<!ELEMENT KIET (DEPARTMENT)>
<!ELEMENT DEPARTMENT (CSE+,MCA+)>
<!ELEMENT MCA (FACULTY+)>
<!ELEMENT FACULTY (NAME,SUBJECT,SEMESTER,SESSION)>
<!ELEMENT NAME (FIRST_NAME,LAST_NAME)>
<!ELEMENT FIRST_NAME (#PCDATA)>
<!ELEMENT LAST_NAME (#PCDATA)>
<!ELEMENT SUBJECT (#PCDATA)>
<!ELEMENT SEMESTER (#PCDATA)>
<!ELEMENT SESSION (#PCDATA)>
<!ATTLIST FACULTY DESIGNATION CDATA #REQUIRED>

=== akhilvofficial9/XML/externaldtd.xml
<?xml version="1.0"?>
<!DOCTYPE KIET SYSTEM 'Kiet.dtd'>
<KIET>
<DEPARTMENT>

<MCA>
<FACULTY DESIGNATION="AP">
<NAME>
<FIRST_NAME> Akhil </FIRST_NAME>
<LAST_NAME> Verma </LAST_NAME>
</NAME>
<SUBJECT> Web Technology </SUBJECT>
<SEMESTER> Fifth</SEMESTER>
<SESSION> A </SESSION>
</FACULTY>

<FACULTY DESIGNATION="Prof">
<NAME>
<FIRST_NAME> Amit </FIRST_NAME>
<LAST_NAME> Sharma </LAST_NAME>
</NAME>
<SUBJECT> C++ </SUBJECT>
<SEMESTER> Third </SEMESTER>
<SESSION>A</SESSION>
</FACULTY>

<FACULTY DESIGNATION="Lecturer">
<NAME>
<FIRST_NAME> Abhi </FIRST_NAME>
<LAST_NAME> Goyal </LAST_NAME>
</NAME>
<SUBJECT> DBMS </SUBJECT>
<SEMESTER> III </SEMESTER>
<SESSION> B </SESSION>
</FACULTY>

</MCA>
</DEPARTMENT>
</KIET>
